[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@vonage/server-sdk"]

[build.environment]
  NODE_VERSION = "18"
  # Disable secrets scanning for Firebase config values (these are public)
  SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,FIREBASE_AUTH_DOMAIN,VITE_FIREBASE_STORAGE_BUCKET,FIREBASE_MESSAGING_ID,VITE_FIREBASE_APP_ID,FIREBASE_API_KEY,apiKey,authDomain,projectId,storageBucket,messagingSenderId,appId"
  # Exclude public configuration files from secrets scanning
  SECRETS_SCAN_OMIT_PATHS = "public/firebase-config.json,src/config/firebase.ts" 