[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  base = "/"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 5173
  publish = "dist"
  autoLaunch = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@vonage/server-sdk"]

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  NPM_TOKEN = ""
  NPM_CONFIG_PRODUCTION = "false" 